### PR TITLE
Implements truely Strict HRM Grammar

### LINKED ISSUE #7: Instructions are case sensitive
The following fails:

```
a:
    inbox
    jump a
```

While the following succeeds:

```
a:
    INBOX
    JUMP a
```

### LINKED ISSUE #8: Labels should match in-game requirements
Labels MUST:
- Start with a letter (`[a-zA-Z]`)
- Be comprised only of letters and numbers (`[a-zA-Z0-9]`)
- Be case-sensitive

Label statements MUST:
- Appear on their own line

(Appears to be no line length, nor label length restrictions.)

### LINKED ISSUE #9: Instructions may be internally separated along newlines but may not be mixed on a line
The following should succeed:

```
a:
    INBOX
    COPYTO
    [ 8 ]
    OUTBOX
    JUMP
a
```

The following should fail:

```
a:
    INBOX
    COPYTO
    [8]       OUTBOX
    JUMP
a
```

### PR DESCRIPTION
**Pull request by sixlettervariables**
- Instructions and their arguments can be split between lines
- Instructions cannot occupy the same line
- Instructions must be uppercase
- Labels may not be keywords (case-sensitive)
- Labels must start with a letter and may end with any number of letters
  or digits
- Bumps to 2.2.0 for npm

Fixes #9
Fixes #8
Fixes #7

### CODE REVIEW

**Comment by nrkn** [comment]
Nice!

**Comment by nrkn** [comment]
There are some cases where instructions can occupy the same line, this is valid for Mail Room:

INBOX OUTBOX INBOX OUTBOX INBOX OUTBOX

**Comment by sixlettervariables** [comment]
Interesting, I could not get that to work (but I may have had something else wrong in my inputs).

**Comment by sixlettervariables** [comment]
I've got a new success case to add to my tests!

```
-- HUMAN RESOURCE MACHINE PROGRAM --

inbox: INBOX OUTBOX otherinbox: INBOX
outbox: ADD 2
INBOX ADD 3
OUTBOX COPYFROM [  2
-- THIS IS NOT AS BAD AS IT LOOKS ]
                  ]
INBOX outbox2: JUMPZ otherinbox
INBOX DEFINE 
      LABEL 
      -- WITH A COMMENT OR TWO
      -- OF COURSE
  24
eJxTY2BgqJG51fBbpm2Bqbzo6tVKj7fMU1+z+6zu+72Wprl7MqwTN0c7nFsq6LJz2hGP6XV7vN2LN/pX
ZQpFv44TLM6M7S7NTdhbda7crFat82Od/WzD+sdbvtSu2FFdrbWro2zFjrl5shsL0wVXNCYenOMfk9t3
LXJ+S3hkV+mF6D9ZTom5CTqZsqE8pTyeHH3vjZXmLNYWX6CmO3mhnjHDKBgFo4AuAAAdEES6;
JUMPZ outbox2
JUMPN inbox
JUMP outbox
```

**Comment by nrkn** [comment]
So the general case is that an instruction cannot follow an argument on the same line?

**Comment by sixlettervariables** [comment]
Yes, but labels apparently can follow too.

**Comment by nrkn** [comment]
Unrelated - your user name - a reference to Fortran?

**Comment by sixlettervariables** [comment]
Excellent guess. Day job calls upon working knowledge of F66/77/90.

**Comment by nrkn** [comment]
Oh fun! I've done some Fortran and even some Cobol, but not for many, many years now.

**Pull request merged**
